# Generated by Django 5.1.4 on 2024-12-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_set_superuser_type'),
        ('core', 'set_superuser_type'),
    ]

    operations = [
    ]
