# Generated by Django 5.1.4 on 2024-12-17 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_0003_auto_set_superuser_type_set_superuser_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'ordering': ['name'], 'verbose_name_plural': 'commodities'},
        ),
        migrations.AddField(
            model_name='commodity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commodity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
