# Generated by Django 5.1.4 on 2024-12-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_commodity_options_commodity_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('commodity', 'market', 'date')},
        ),
    ]
